=begin 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end 

def fibonacci(fib_num_limit)
	previous = 1
	result = 1
	i = 0
	even_sum = 0
	while (result + previous) <= fib_num_limit
		sum = result + previous
		previous = result
		result = sum
		i += 1
		# keeps total of even fibonacci numbers
		if result % 2 == 0
			even_sum += result
		end
	end
	return even_sum 
end


puts fibonacci(4000000)
